component::ServoMotor Class Reference
#include <ServoMotor.h>
Public Member Functions
ServoMotor (const io::Pin &ar_pin, const uint16_t &ar_pulseCycle=0, const uint16_t &ar_pulseWidthMin=0, const uint16_t &ar_pulseWidthMid=0, const uint16_t &ar_pulseWidthMax=0)
~ServoMotor ()
void on ()
Turn servo motor On.
void off ()
Turn servo motor Off.
void toggle ()
Toggle servo motor state.
uint16_t computePulseCycleCount (const uint16_t &ar_clockPrescaler)
uint16_t computePulseWidthMinCount (const uint16_t &ar_clockPrescaler)
uint16_t computePulseWidthMidCount (const uint16_t &ar_clockPrescaler)
uint16_t computePulseWidthMaxCount (const uint16_t &ar_clockPrescaler)
uint16_t computeRotationAngleCount (const uint8_t &ar_angle_deg, const uint16_t &ar_clockPrescaler)
void rotate (core::TimerCounter1 &ar_timerCounter1, const uint8_t &ar_angle_deg, const core::channel &ar_channel=core::channel::A)
void connect (core::TimerCounter1 &ar_timerCounter1, const core::channel &ar_channel=core::channel::A)
void disconnect (core::TimerCounter1 &ar_timerCounter1, const core::channel &ar_channel=core::channel::A)
Private Attributes
io::Pin m_pin
pin object
uint16_t m_pulseCycle
pulse cycle [us]
uint16_t m_pulseWidthMin
pulse width min [us]
uint16_t m_pulseWidthMid
pulse width mid [us]
uint16_t m_pulseWidthMax
pulse width max [us]
Detailed Description
Definition at line 138 of file ServoMotor.h.
Constructor & Destructor Documentation
ServoMotor()
component::ServoMotor::ServoMotor (const io::Pin & ar_pin, const uint16_t & ar_pulseCycle = 0, const uint16_t & ar_pulseWidthMin = 0, const uint16_t & ar_pulseWidthMid = 0, const uint16_t & ar_pulseWidthMax = 0)
Definition at line 5 of file ServoMotor.cpp.
                      : m_pin(ar_pin),
                        m_pulseCycle(ar_pulseCycle),
                        m_pulseWidthMin(ar_pulseWidthMin),
                        m_pulseWidthMid(ar_pulseWidthMid),
                        m_pulseWidthMax(ar_pulseWidthMax)
{
    m_pin.toOutput();
}
References m_pin, and io::Pin::toOutput().
 ServoMotor()
component::ServoMotor::~ServoMotor ()
Definition at line 20 of file ServoMotor.cpp.
{
}
Member Function Documentation
computePulseCycleCount()
uint16_t component::ServoMotor::computePulseCycleCount (const uint16_t & ar_clockPrescaler)
Definition at line 44 of file ServoMotor.cpp.
{
    return SERVOMOTOR_TIMER_PULSE_WIDTH_COUNT(m_pulseCycle,ar_clockPrescaler);
}
References SERVOMOTOR_TIMER_PULSE_WIDTH_COUNT.
computePulseWidthMaxCount()
uint16_t component::ServoMotor::computePulseWidthMaxCount (const uint16_t & ar_clockPrescaler)
Definition at line 54 of file ServoMotor.cpp.
{
    return SERVOMOTOR_TIMER_PULSE_WIDTH_COUNT(m_pulseWidthMax,ar_clockPrescaler);
}
References SERVOMOTOR_TIMER_PULSE_WIDTH_COUNT.
computePulseWidthMidCount()
uint16_t component::ServoMotor::computePulseWidthMidCount (const uint16_t & ar_clockPrescaler)
Definition at line 59 of file ServoMotor.cpp.
{
    return SERVOMOTOR_TIMER_PULSE_WIDTH_COUNT(m_pulseWidthMid,ar_clockPrescaler);
}
References SERVOMOTOR_TIMER_PULSE_WIDTH_COUNT.
computePulseWidthMinCount()
uint16_t component::ServoMotor::computePulseWidthMinCount (const uint16_t & ar_clockPrescaler)
Definition at line 49 of file ServoMotor.cpp.
{
    return SERVOMOTOR_TIMER_PULSE_WIDTH_COUNT(m_pulseWidthMin,ar_clockPrescaler);
}
References SERVOMOTOR_TIMER_PULSE_WIDTH_COUNT.
computeRotationAngleCount()
uint16_t component::ServoMotor::computeRotationAngleCount (const uint8_t & ar_angle_deg, const uint16_t & ar_clockPrescaler)
Definition at line 64 of file ServoMotor.cpp.
{
    return static_cast<uint16_t>(SERVOMOTOR_TIMER_ANGLE_COUNT(ar_angle_deg,static_cast<long>(computePulseWidthMinCount(ar_clockPrescaler)),static_cast<long>(computePulseWidthMidCount(ar_clockPrescaler)),static_cast<long>(computePulseWidthMaxCount(ar_clockPrescaler))));
}
References SERVOMOTOR_TIMER_ANGLE_COUNT.
connect()
void component::ServoMotor::connect (core::TimerCounter1 & ar_timerCounter1, const core::channel & ar_channel = core::channel::A)
Definition at line 85 of file ServoMotor.cpp.
{
    ar_timerCounter1.setInputCaptureRegister(computePulseCycleCount(ar_timerCounter1.getClockPrescaler()));
    ar_timerCounter1.selectOperationMode(core::operationMode::fast_PWM_ICR);
    ar_timerCounter1.selectCompareOutputMode(ar_channel, core::compareOutputMode::clear);
    ar_timerCounter1.setCounter(0);
}
References core::clear, core::fast_PWM_ICR, core::TimerCounter1::getClockPrescaler(), core::TimerCounter1::selectCompareOutputMode(), core::TimerCounter1::selectOperationMode(), core::TimerCounter1::setCounter(), and core::TimerCounter1::setInputCaptureRegister().
disconnect()
void component::ServoMotor::disconnect (core::TimerCounter1 & ar_timerCounter1, const core::channel & ar_channel = core::channel::A)
Definition at line 97 of file ServoMotor.cpp.
{
    ar_timerCounter1.selectCompareOutputMode(ar_channel, core::compareOutputMode::normal);
    // stop timer
    ar_timerCounter1.stop();
}
References core::normal, core::TimerCounter1::selectCompareOutputMode(), and core::TimerCounter1::stop().
off()
void component::ServoMotor::off ()
Turn servo motor Off.
Definition at line 33 of file ServoMotor.cpp.
{
    m_pin.setLow();
}
on()
void component::ServoMotor::on ()
Turn servo motor On.
Definition at line 28 of file ServoMotor.cpp.
{
    m_pin.setHigh();
}
rotate()
void component::ServoMotor::rotate (core::TimerCounter1 & ar_timerCounter1, const uint8_t & ar_angle_deg, const core::channel & ar_channel = core::channel::A)
Definition at line 71 of file ServoMotor.cpp.
{
    ar_timerCounter1.setOutputCompareRegister(ar_channel, computeRotationAngleCount(ar_angle_deg,ar_timerCounter1.getClockPrescaler()));
    // start timer
    ar_timerCounter1.start();
}
References core::TimerCounter1::getClockPrescaler(), core::TimerCounter1::setOutputCompareRegister(), and core::TimerCounter1::start().
toggle()
void component::ServoMotor::toggle ()
Toggle servo motor state.
Definition at line 38 of file ServoMotor.cpp.
{
    m_pin.toggle();
}
Member Data Documentation
m_pin
io::Pin component::ServoMotor::m_pin [private]
pin object
Definition at line 188 of file ServoMotor.h.
Referenced by ServoMotor().
m_pulseCycle
uint16_t component::ServoMotor::m_pulseCycle [private]
pulse cycle [us]
Definition at line 190 of file ServoMotor.h.
m_pulseWidthMax
uint16_t component::ServoMotor::m_pulseWidthMax [private]
pulse width max [us]
Definition at line 196 of file ServoMotor.h.
m_pulseWidthMid
uint16_t component::ServoMotor::m_pulseWidthMid [private]
pulse width mid [us]
Definition at line 194 of file ServoMotor.h.
m_pulseWidthMin
uint16_t component::ServoMotor::m_pulseWidthMin [private]
pulse width min [us]
Definition at line 192 of file ServoMotor.h.