core::TimerCounter1 Class Reference
#include <TimerCounter1.h>
Public Member Functions
void selectOperationMode (const operationMode &ar_operationMode) override
void start () override
void stop () override
void selectClockSource (const clockSource &ar_clockSource) override
void selectCompareOutputMode (const channel &ar_channel, const compareOutputMode &ar_compareOutputMode) override
void setCounter (const uint16_t &ar_dataBuffer) override
uint16_t getCounter () const override
void setOutputCompareRegister (const channel &ar_channel, const uint16_t &ar_dataBuffer) override
uint16_t getOutputCompareRegister (const channel &ar_channel) const override
void setInputCaptureRegister (const uint16_t &ar_dataBuffer)
uint16_t getInputCaptureRegister () const
void enableOutputCompareMatchInterrupt (const channel &ar_channel, const uint8_t a_enable) override
void enableOverflowInterrupt (const uint8_t a_enable) override
void enableInputCaptureInterrupt (const uint8_t a_enable)
uint16_t getClockPrescaler () override
Static Public Member Functions
static TimerCounter1 & getInstance (const channel &ar_channel=channel::A, const operationMode &ar_operationMode=operationMode::normal, const clockSource &ar_clockSource=clockSource::noClock, const compareOutputMode &ar_compareOutputMode=compareOutputMode::normal)
static void outputCompareMatchAServiceRoutine () __asm__(STR(TIMER1_COM_CHANNEL_A_INTERRUPT)) __attribute__((__signal__
static void outputCompareMatchBServiceRoutine () __asm__(STR(TIMER1_COM_CHANNEL_B_INTERRUPT)) __attribute__((__signal__
static void overflowServiceRoutine () __asm__(STR(TIMER1_OVERFLOW_INTERRUPT)) __attribute__((__signal__
static void inputCaptureServiceRoutine () __asm__(STR(TIMER1_INPUT_CAPTURE_INTERRUPT)) __attribute__((__signal__
Public Attributes
static void __used__
static void __externally_visible__
Private Member Functions
TimerCounter1 (const channel &ar_channel, const operationMode &ar_operationMode, const clockSource &ar_clockSource, const compareOutputMode &ar_compareOutputMode)
~TimerCounter1 ()
TimerCounter1 (const TimerCounter1 &)
Overried Copy constructor.
const TimerCounter1 & operator= (const TimerCounter1 &)
Override assign operator.
Private Attributes
uint16_t m_clockPrescaler
uint8_t m_clockSource
Detailed Description
Definition at line 279 of file TimerCounter1.h.
Constructor & Destructor Documentation
TimerCounter1() [1/2]
core::TimerCounter1::TimerCounter1 (const channel & ar_channel, const operationMode & ar_operationMode, const clockSource & ar_clockSource, const compareOutputMode & ar_compareOutputMode) [private]
Definition at line 20 of file TimerCounter1.cpp.
{
    core::MCU::enableTimerCounter1(1);
    stop();
    selectOperationMode(ar_operationMode);
    selectClockSource(ar_clockSource);
    selectCompareOutputMode(ar_channel,ar_compareOutputMode);
}
References core::MCU::enableTimerCounter1().
 TimerCounter1()
core::TimerCounter1::~TimerCounter1 () [private]
Definition at line 33 of file TimerCounter1.cpp.
{
}
TimerCounter1() [2/2]
core::TimerCounter1::TimerCounter1 (const TimerCounter1 &) [private]
Overried Copy constructor.
Member Function Documentation
enableInputCaptureInterrupt()
void core::TimerCounter1::enableInputCaptureInterrupt (const uint8_t a_enable)
Definition at line 309 of file TimerCounter1.cpp.
{
    if (a_enable) {
        TIMER1_ENABLE_INPUT_CAPTURE_INTERRUPT;
    } else {
        TIMER1_DISABLE_INPUT_CAPTURE_INTERRUPT;
    }
}
References TIMER1_DISABLE_INPUT_CAPTURE_INTERRUPT, and TIMER1_ENABLE_INPUT_CAPTURE_INTERRUPT.
enableOutputCompareMatchInterrupt()
void core::TimerCounter1::enableOutputCompareMatchInterrupt (const channel & ar_channel, const uint8_t a_enable) [override], [virtual]
Implements core::TimerCounter.
Definition at line 260 of file TimerCounter1.cpp.
{
    switch (ar_channel)
    {
        case core::channel::A:
        {
            if (a_enable) {
                TIMER1_ENABLE_COM_CHANNEL_A_INTERRUPT;
            } else {
                TIMER1_DISABLE_COM_CHANNEL_A_INTERRUPT;
            }
            break;
        }
        case core::channel::B:
        {
            if (a_enable) {
                TIMER1_ENABLE_COM_CHANNEL_B_INTERRUPT;
            } else {
                TIMER1_DISABLE_COM_CHANNEL_B_INTERRUPT;
            }
            break;
        }
    }
}
References core::A, core::B, TIMER1_DISABLE_COM_CHANNEL_A_INTERRUPT, TIMER1_DISABLE_COM_CHANNEL_B_INTERRUPT, TIMER1_ENABLE_COM_CHANNEL_A_INTERRUPT, and TIMER1_ENABLE_COM_CHANNEL_B_INTERRUPT.
enableOverflowInterrupt()
void core::TimerCounter1::enableOverflowInterrupt (const uint8_t a_enable) [override], [virtual]
Implements core::TimerCounter.
Definition at line 295 of file TimerCounter1.cpp.
{
    if (a_enable) {
        TIMER1_ENABLE_OVERFLOW_INTERRUPT;
    } else {
        TIMER1_DISABLE_OVERFLOW_INTERRUPT;
    }
}
References TIMER1_DISABLE_OVERFLOW_INTERRUPT, and TIMER1_ENABLE_OVERFLOW_INTERRUPT.
getClockPrescaler()
uint16_t core::TimerCounter1::getClockPrescaler () [override], [virtual]
Implements core::TimerCounter.
Definition at line 186 of file TimerCounter1.cpp.
{
    return m_clockPrescaler;
}
Referenced by component::ServoMotor::connect(), and component::ServoMotor::rotate().
getCounter()
uint16_t core::TimerCounter1::getCounter () const [override], [virtual]
Implements core::TimerCounter.
Definition at line 221 of file TimerCounter1.cpp.
{
    return TCNT1;
}
getInputCaptureRegister()
uint16_t core::TimerCounter1::getInputCaptureRegister () const
Definition at line 327 of file TimerCounter1.cpp.
{
    return ICR1;
}
getInstance()
core::TimerCounter1 & core::TimerCounter1::getInstance (const channel & ar_channel = channel::A, const operationMode & ar_operationMode = operationMode::normal, const clockSource & ar_clockSource = clockSource::noClock, const compareOutputMode & ar_compareOutputMode = compareOutputMode::normal) [static]
Definition at line 5 of file TimerCounter1.cpp.
{
    static TimerCounter1 l_instance(ar_channel,
                                    ar_operationMode,
                                    ar_clockSource,
                                    ar_compareOutputMode);
    return l_instance;
}
getOutputCompareRegister()
uint16_t core::TimerCounter1::getOutputCompareRegister (const channel & ar_channel) const [override], [virtual]
Implements core::TimerCounter.
Definition at line 245 of file TimerCounter1.cpp.
{
    switch (ar_channel)
    {
        case core::channel::A:
        {
            return OCR1A;
        }
        case core::channel::B:
        {
            return OCR1B;
        }
    }
}
References core::A, and core::B.
inputCaptureServiceRoutine()
static void core::TimerCounter1::inputCaptureServiceRoutine () [static]
operator=()
const TimerCounter1& core::TimerCounter1::operator= (const TimerCounter1 &) [private]
Override assign operator.
outputCompareMatchAServiceRoutine()
static void core::TimerCounter1::outputCompareMatchAServiceRoutine () [static]
outputCompareMatchBServiceRoutine()
static void core::TimerCounter1::outputCompareMatchBServiceRoutine () [static]
overflowServiceRoutine()
static void core::TimerCounter1::overflowServiceRoutine () [static]
selectClockSource()
void core::TimerCounter1::selectClockSource (const clockSource & ar_clockSource) [override], [virtual]
Implements core::TimerCounter.
Definition at line 38 of file TimerCounter1.cpp.
{
    switch (ar_clockSource)
    {
        case core::clockSource::noClock:
        {
            m_clockPrescaler=0;
            m_clockSource=0;
            break;
        }
        case core::clockSource::PS_1:
        {
            m_clockPrescaler=1;
            m_clockSource=1;
            break;
        }
        case core::clockSource::PS_8:
        {
            m_clockPrescaler=8;
            m_clockSource=2;
            break;
        }
        case core::clockSource::PS_64:
        {
            m_clockPrescaler=64;
            m_clockSource=3;
            break;
        }
        case core::clockSource::PS_256:
        {
            m_clockPrescaler=256;
            m_clockSource=4;
            break;
        }
        case core::clockSource::PS_1024:
        {
            m_clockPrescaler=1024;
            m_clockSource=5;
            break;
        }
        case core::clockSource::extern_Clock_T0_Falling_Edge:
        {
            m_clockPrescaler=0;
            m_clockSource=6;
            break;
        }
        case core::clockSource::extern_Clock_T0_Rising_Edge:
        {
            m_clockPrescaler=0;
            m_clockSource=7;
            break;
        }
    }
}
References core::extern_Clock_T0_Falling_Edge, core::extern_Clock_T0_Rising_Edge, core::noClock, core::PS_1, core::PS_1024, core::PS_256, core::PS_64, and core::PS_8.
selectCompareOutputMode()
void core::TimerCounter1::selectCompareOutputMode (const channel & ar_channel, const compareOutputMode & ar_compareOutputMode) [override], [virtual]
Implements core::TimerCounter.
Definition at line 197 of file TimerCounter1.cpp.
{
    switch (ar_channel)
    {
        case core::channel::A:
        {
            TIMER1_SELECT_COM_CHANNEL_A(static_cast<uint8_t>(ar_compareOutputMode));
            break;
        }
        case core::channel::B:
        {
            TIMER1_SELECT_COM_CHANNEL_B(static_cast<uint8_t>(ar_compareOutputMode));
            break;
        }
    }
}
References core::A, core::B, TIMER1_SELECT_COM_CHANNEL_A, and TIMER1_SELECT_COM_CHANNEL_B.
Referenced by component::ServoMotor::connect(), and component::ServoMotor::disconnect().
selectOperationMode()
void core::TimerCounter1::selectOperationMode (const operationMode & ar_operationMode) [override], [virtual]
Implements core::TimerCounter.
Definition at line 95 of file TimerCounter1.cpp.
{
    switch (ar_operationMode)
    {
        case core::operationMode::normal:
        {
            TIMER1_SELECT_OPERATION_MODE(0);
            break;
        }
        case core::operationMode::PWM_PC_8bit:
        {
            TIMER1_SELECT_OPERATION_MODE(1);
            break;
        }
        case core::operationMode::PWM_PC_9bit:
        {
            TIMER1_SELECT_OPERATION_MODE(2);
            break;
        }
        case core::operationMode::PWM_PC_10bit:
        {
            TIMER1_SELECT_OPERATION_MODE(3);
            break;
        }
        case core::operationMode::CTC_OCR:
        {
            TIMER1_SELECT_OPERATION_MODE(4);
            break;
        }
        case core::operationMode::fast_PWM_8bit:
        {
            TIMER1_SELECT_OPERATION_MODE(5);
            break;
        }
        case core::operationMode::fast_PWM_9bit:
        {
            TIMER1_SELECT_OPERATION_MODE(6);
            break;
        }
        case core::operationMode::fast_PWM_10bit:
        {
            TIMER1_SELECT_OPERATION_MODE(7);
            break;
        }
        case core::operationMode::PWM_PFC_ICR:
        {
            TIMER1_SELECT_OPERATION_MODE(8);
            break;
        }
        case core::operationMode::PWM_PFC_OCR:
        {
            TIMER1_SELECT_OPERATION_MODE(9);
            break;
        }
        case core::operationMode::PWM_PC_ICR:
        {
            TIMER1_SELECT_OPERATION_MODE(10);
            break;
        }
        case core::operationMode::PWM_PC_OCR:
        {
            TIMER1_SELECT_OPERATION_MODE(11);
            break;
        }
        case core::operationMode::CTC_ICR:
        {
            TIMER1_SELECT_OPERATION_MODE(12);
            break;
        }
        case core::operationMode::fast_PWM_ICR:
        {
            TIMER1_SELECT_OPERATION_MODE(14);
            break;
        }
        case core::operationMode::fast_PWM_OCR:
        {
            TIMER1_SELECT_OPERATION_MODE(15);
            break;
        }
    }
}
References core::CTC_ICR, core::CTC_OCR, core::fast_PWM_10bit, core::fast_PWM_8bit, core::fast_PWM_9bit, core::fast_PWM_ICR, core::fast_PWM_OCR, core::normal, core::PWM_PC_10bit, core::PWM_PC_8bit, core::PWM_PC_9bit, core::PWM_PC_ICR, core::PWM_PC_OCR, core::PWM_PFC_ICR, core::PWM_PFC_OCR, and TIMER1_SELECT_OPERATION_MODE.
Referenced by component::ServoMotor::connect().
setCounter()
void core::TimerCounter1::setCounter (const uint16_t & ar_dataBuffer) [override], [virtual]
Implements core::TimerCounter.
Definition at line 216 of file TimerCounter1.cpp.
{
    TCNT1 = ar_dataBuffer;
}
Referenced by component::ServoMotor::connect().
setInputCaptureRegister()
void core::TimerCounter1::setInputCaptureRegister (const uint16_t & ar_dataBuffer)
Definition at line 321 of file TimerCounter1.cpp.
{
    ICR1 = ar_dataBuffer;
}
Referenced by component::ServoMotor::connect().
setOutputCompareRegister()
void core::TimerCounter1::setOutputCompareRegister (const channel & ar_channel, const uint16_t & ar_dataBuffer) [override], [virtual]
Implements core::TimerCounter.
Definition at line 226 of file TimerCounter1.cpp.
{
    switch (ar_channel)
    {
        case core::channel::A:
        {
            OCR1A = ar_dataBuffer;
            break;
        }
        case core::channel::B:
        {
            OCR1B = ar_dataBuffer;
            break;
        }
    }
}
References core::A, and core::B.
Referenced by component::ServoMotor::rotate().
start()
void core::TimerCounter1::start () [override], [virtual]
Implements core::TimerCounter.
Definition at line 181 of file TimerCounter1.cpp.
{
    TIMER1_SELECT_CLOCK_SOURCE(m_clockSource);
}
References TIMER1_SELECT_CLOCK_SOURCE.
Referenced by component::ServoMotor::rotate().
stop()
void core::TimerCounter1::stop () [override], [virtual]
Implements core::TimerCounter.
Definition at line 191 of file TimerCounter1.cpp.
{
    TIMER1_STOP;
}
References TIMER1_STOP.
Referenced by component::ServoMotor::disconnect().
Member Data Documentation
__externally_visible__
static void core::TimerCounter1::__externally_visible__
Definition at line 320 of file TimerCounter1.h.
__used__
static void core::TimerCounter1::__used__
Definition at line 320 of file TimerCounter1.h.
m_clockPrescaler
uint16_t core::TimerCounter1::m_clockPrescaler [private]
Definition at line 349 of file TimerCounter1.h.
m_clockSource
uint8_t core::TimerCounter1::m_clockSource [private]
Definition at line 351 of file TimerCounter1.h.