io::SPI Class Reference
#include <SPI.h>
Public Member Functions
void selectDataMode (const dataMode &ar_dataMode)
void selectDataOrder (const dataOrder &ar_dataOrder)
void selectOperationMode (const operationMode &ar_operationMode)
void selectClockPrescaler (const clockPrescaler &ar_clockPrescaler)
void selectSlave (const uint8_t a_select)
uint8_t writeCollision ()
Is there write collision.
uint8_t transferComplete ()
Is serial transfer complete.
void masterSendByte (const uint8_t &ar_byte)
void masterReceiveByte (uint8_t &ar_byte)
void slaveReceiveByte (uint8_t &ar_byte)
Static Public Member Functions
static SPI & getInstance (const io::Pin &ar_pinSCK, const io::Pin &ar_pinMISO, const io::Pin &ar_pinMOSI, const io::Pin &ar_pinSS)
static void enableTransferCompleteInterrupt (const uint8_t a_enable)
static void transferCompleteServiceRoutine () __asm__(STR(SPI_TRANSFER_COMPLETE_INTERRUPT)) __attribute__((__signal__
Serial transfer complete ISR.
Public Attributes
static void __used__
static void __externally_visible__
Private Member Functions
SPI (const io::Pin &ar_pinSCK, const io::Pin &ar_pinMISO, const io::Pin &ar_pinMOSI, const io::Pin &ar_pinSS)
Constructor.
~SPI ()
Destructor.
SPI (const SPI &)
Overried Copy constructor.
const SPI & operator= (const SPI &)
Override assign operator.
Private Attributes
io::Pin m_pinSCK
pin object
io::Pin m_pinMISO
pin object
io::Pin m_pinMOSI
pin object
io::Pin m_pinSS
pin object
Static Private Attributes
static volatile uint8_t m_data = 0
Detailed Description
Definition at line 86 of file SPI.h.
Constructor & Destructor Documentation
SPI() [1/2]
io::SPI::SPI (const io::Pin & ar_pinSCK, const io::Pin & ar_pinMISO, const io::Pin & ar_pinMOSI, const io::Pin & ar_pinSS) [private]
Constructor.
Initalizes the USART0 object
@param ar_transMode defines transmission mode
@param ar_comMode defines communication mode
@param ar_frameSize defines data frame size
@param ar_stopBit defines number of stop bits
@param ar_parityMode defines parity mode
Definition at line 22 of file SPI.cpp.
        : m_pinSCK(ar_pinSCK),
          m_pinMISO(ar_pinMISO),
          m_pinMOSI(ar_pinMOSI),
          m_pinSS(ar_pinSS)
{
    core::MCU::enableSPI(1);
    sei();
    enableTransferCompleteInterrupt(1);
}
References core::MCU::enableSPI(), and enableTransferCompleteInterrupt().
 SPI()
io::SPI::~SPI () [private]
Destructor.
Definition at line 37 of file SPI.cpp.
{
}
SPI() [2/2]
io::SPI::SPI (const SPI &) [private]
Overried Copy constructor.
Member Function Documentation
enableTransferCompleteInterrupt()
void io::SPI::enableTransferCompleteInterrupt (const uint8_t a_enable) [static]
Definition at line 110 of file SPI.cpp.
{
    if (a_enable) {
        SPI_ENABLE_TRANSFER_COMPLETE_INTERRUPT;
    } else {
        SPI_DISABLE_TRANSFER_COMPLETE_INTERRUPT;
    }
}
References SPI_DISABLE_TRANSFER_COMPLETE_INTERRUPT, and SPI_ENABLE_TRANSFER_COMPLETE_INTERRUPT.
Referenced by SPI().
getInstance()
io::SPI & io::SPI::getInstance (const io::Pin & ar_pinSCK, const io::Pin & ar_pinMISO, const io::Pin & ar_pinMOSI, const io::Pin & ar_pinSS) [static]
Definition at line 8 of file SPI.cpp.
{
    static SPI l_instance(ar_pinSCK,
                          ar_pinMISO,
                          ar_pinMOSI,
                          ar_pinSS);
    return l_instance;
}
masterReceiveByte()
void io::SPI::masterReceiveByte (uint8_t & ar_byte)
Definition at line 147 of file SPI.cpp.
{
    masterSendByte(0);
    ar_byte = m_data;
}
masterSendByte()
void io::SPI::masterSendByte (const uint8_t & ar_byte)
Definition at line 135 of file SPI.cpp.
{
    SPI_DATA_REGISTER = ar_byte;
    selectSlave(1);
    while(!transferComplete()){};
    selectSlave(0);
}
References SPI_DATA_REGISTER.
operator=()
const SPI& io::SPI::operator= (const SPI &) [private]
Override assign operator.
selectClockPrescaler()
void io::SPI::selectClockPrescaler (const clockPrescaler & ar_clockPrescaler)
Definition at line 53 of file SPI.cpp.
{
    SPI_SELECT_CLOCK_PRESCALER(static_cast<uint8_t>(ar_clockPrescaler));
}
References SPI_SELECT_CLOCK_PRESCALER.
selectDataMode()
void io::SPI::selectDataMode (const dataMode & ar_dataMode)
Definition at line 99 of file SPI.cpp.
{
    SPI_SELECT_DATA_MODE(static_cast<uint8_t>(ar_dataMode));
}
References SPI_SELECT_DATA_MODE.
selectDataOrder()
void io::SPI::selectDataOrder (const dataOrder & ar_dataOrder)
Definition at line 104 of file SPI.cpp.
{
    SPI_SELECT_DATA_ORDER(static_cast<uint8_t>(ar_dataOrder));
}
References SPI_SELECT_DATA_ORDER.
selectOperationMode()
void io::SPI::selectOperationMode (const operationMode & ar_operationMode)
Definition at line 59 of file SPI.cpp.
{
    switch (ar_operationMode)
    {
        case operationMode::master:
        {
            m_pinMOSI.toOutput();
            m_pinSCK.toOutput();
            m_pinMISO.toInput(1);
            m_pinSS.toOutput();
            m_pinSS.setHigh();
            SPI_SELECT_MASTER_MODE;
            SPI_ENABLE;
            break;
        }
        case operationMode::slave:
        {
            m_pinMISO.toOutput();
            SPI_SELECT_SLAVE_MODE;
            SPI_ENABLE;
            break;
        }
        case operationMode::submaster:
        {
            m_pinMOSI.toOutput();
            m_pinSCK.toOutput();
            m_pinMISO.toInput(1);
            m_pinSS.toInput(1);
            SPI_SELECT_MASTER_MODE;
            SPI_ENABLE;
            break;
        }
        case operationMode::disable:
        {
            SPI_DISABLE;
            break;
        }
    }
}
References io::disable, io::master, io::slave, SPI_DISABLE, SPI_ENABLE, SPI_SELECT_MASTER_MODE, SPI_SELECT_SLAVE_MODE, and io::submaster.
selectSlave()
void io::SPI::selectSlave (const uint8_t a_select)
Definition at line 119 of file SPI.cpp.
{
    if (a_select) {
        m_pinSS.setLow();
    } else {
        m_pinSS.setHigh();
    }
}
slaveReceiveByte()
void io::SPI::slaveReceiveByte (uint8_t & ar_byte)
Definition at line 154 of file SPI.cpp.
{
    ar_byte = m_data;
}
transferComplete()
uint8_t io::SPI::transferComplete ()
Is serial transfer complete.
Definition at line 48 of file SPI.cpp.
{
    return (SPI_STATUS_REGISTER & (1 << SPI_TRANSFER_COMPLETE));
}
References SPI_STATUS_REGISTER, and SPI_TRANSFER_COMPLETE.
transferCompleteServiceRoutine()
void io::SPI::transferCompleteServiceRoutine () [static]
Serial transfer complete ISR.
Definition at line 129 of file SPI.cpp.
{
        m_data = SPI_DATA_REGISTER;
}
References SPI_DATA_REGISTER.
writeCollision()
uint8_t io::SPI::writeCollision ()
Is there write collision.
Definition at line 42 of file SPI.cpp.
{
    return (SPI_STATUS_REGISTER & (1 << SPI_WRITE_COLLISION));
}
References SPI_STATUS_REGISTER, and SPI_WRITE_COLLISION.
Member Data Documentation
__externally_visible__
void io::SPI::__externally_visible__
Definition at line 124 of file SPI.h.
__used__
void io::SPI::__used__
Definition at line 124 of file SPI.h.
m_data
volatile uint8_t io::SPI::m_data = 0 [static], [private]
Definition at line 154 of file SPI.h.
m_pinMISO
io::Pin io::SPI::m_pinMISO [private]
pin object
Definition at line 157 of file SPI.h.
m_pinMOSI
io::Pin io::SPI::m_pinMOSI [private]
pin object
Definition at line 158 of file SPI.h.
m_pinSCK
io::Pin io::SPI::m_pinSCK [private]
pin object
Definition at line 156 of file SPI.h.
m_pinSS
io::Pin io::SPI::m_pinSS [private]
pin object
Definition at line 159 of file SPI.h.