core::MCU Class Reference
#include <MCU.h>
Static Public Member Functions
static void init ()
static void selectSleepMode (const sleepMode &a_sleepMode)
static void goToSleep (const BODMode &a_BODMode)
static void sleepEnable (const uint8_t ar_enable)
static void enableUSART0 (const uint8_t a_enable)
static void enableTimerCounter0 (const uint8_t a_enable)
static void enableTimerCounter1 (const uint8_t a_enable)
static void enableTimerCounter2 (const uint8_t a_enable)
static void enableTWI (const uint8_t a_enable)
static void enableSPI (const uint8_t a_enable)
static void enableADC (const uint8_t a_enable)
static void disableBOD ()
Detailed Description
Definition at line 91 of file MCU.h.
Member Function Documentation
disableBOD()
void core::MCU::disableBOD () [static]
Definition at line 126 of file MCU.cpp.
{
    MCU_BOD_DISABLE;
}
References MCU_BOD_DISABLE.
enableADC()
void core::MCU::enableADC (const uint8_t a_enable) [static]
Definition at line 117 of file MCU.cpp.
{
    if (a_enable) {
        MCU_ADC_ENABLE;
    } else {
        MCU_ADC_DISABLE;
    }
}
References MCU_ADC_DISABLE, and MCU_ADC_ENABLE.
Referenced by core::ADConverter::ADConverter(), and init().
enableSPI()
void core::MCU::enableSPI (const uint8_t a_enable) [static]
Definition at line 107 of file MCU.cpp.
{
    if (a_enable) {
        MCU_SPI_ENABLE;
    } else {
        MCU_SPI_DISABLE;
    }
}
References MCU_SPI_DISABLE, and MCU_SPI_ENABLE.
Referenced by init(), and io::SPI::SPI().
enableTimerCounter0()
void core::MCU::enableTimerCounter0 (const uint8_t a_enable) [static]
Definition at line 67 of file MCU.cpp.
{
    if (a_enable) {
        MCU_TIMER0_ENABLE;
    } else {
        MCU_TIMER0_DISABLE;
    }
}
References MCU_TIMER0_DISABLE, and MCU_TIMER0_ENABLE.
Referenced by init(), and core::TimerCounter0::TimerCounter0().
enableTimerCounter1()
void core::MCU::enableTimerCounter1 (const uint8_t a_enable) [static]
Definition at line 77 of file MCU.cpp.
{
    if (a_enable) {
        MCU_TIMER1_ENABLE;
    } else {
        MCU_TIMER1_DISABLE;
    }
}
References MCU_TIMER1_DISABLE, and MCU_TIMER1_ENABLE.
Referenced by init(), and core::TimerCounter1::TimerCounter1().
enableTimerCounter2()
void core::MCU::enableTimerCounter2 (const uint8_t a_enable) [static]
Definition at line 87 of file MCU.cpp.
{
    if (a_enable) {
        MCU_TIMER2_ENABLE;
    } else {
        MCU_TIMER2_DISABLE;
    }
}
References MCU_TIMER2_DISABLE, and MCU_TIMER2_ENABLE.
Referenced by init(), and core::TimerCounter2::TimerCounter2().
enableTWI()
void core::MCU::enableTWI (const uint8_t a_enable) [static]
Definition at line 97 of file MCU.cpp.
{
    if (a_enable) {
        MCU_TWI_ENABLE;
    } else {
        MCU_TWI_DISABLE;
    }
}
References MCU_TWI_DISABLE, and MCU_TWI_ENABLE.
Referenced by init().
enableUSART0()
void core::MCU::enableUSART0 (const uint8_t a_enable) [static]
Definition at line 57 of file MCU.cpp.
{
    if (a_enable) {
        MCU_USART0_ENABLE;
    } else {
        MCU_USART0_DISABLE;
    }
}
References MCU_USART0_DISABLE, and MCU_USART0_ENABLE.
Referenced by init(), and io::USART0::USART0().
goToSleep()
void core::MCU::goToSleep (const BODMode & a_BODMode) [static]
Definition at line 21 of file MCU.cpp.
{
    cli();
    switch (a_BODMode)
    {
        case core::BODMode::enabled:
        {
            sleepEnable(1);
            sei();
            sleep_cpu();
            sleepEnable(0);
            break;
        }
        case core::BODMode::disabled:
        {
            sleepEnable(1);
            disableBOD();
            sei();
            sleep_cpu();
            sleepEnable(0);
            break;
        }
    }
}
References core::disabled, and core::enabled.
init()
void core::MCU::init () [static]
Definition at line 3 of file MCU.cpp.
{
    enableUSART0(0);
    enableTimerCounter0(0);
    enableTimerCounter1(0);
    enableTimerCounter2(0);
    enableTWI(0);
    enableSPI(0);
    enableADC(0);
}
References enableADC(), enableSPI(), enableTimerCounter0(), enableTimerCounter1(), enableTimerCounter2(), enableTWI(), and enableUSART0().
selectSleepMode()
void core::MCU::selectSleepMode (const sleepMode & a_sleepMode) [static]
Definition at line 15 of file MCU.cpp.
{
    MCU_SELECT_SLEEP_MODE(static_cast<uint8_t>(a_sleepMode));
}
References MCU_SELECT_SLEEP_MODE.
sleepEnable()
void core::MCU::sleepEnable (const uint8_t ar_enable) [static]
Definition at line 47 of file MCU.cpp.
{
    if (a_enable) {
        MCU_SLEEP_ENABLE;
    } else {
        MCU_SLEEP_DISABLE;
    }
}
References MCU_SLEEP_DISABLE, and MCU_SLEEP_ENABLE.