io::Pin Class Reference
#include <Pin.h>
Public Member Functions
Pin (const uint8_t a_pinNumber, const Port &ar_portName)
Constructor.
~Pin ()
Destructor.
void toOutput ()
Configures pin to output.
void toInput (const uint8_t &ar_useInternalPullUp)
Configures pin to input.
void setLow ()
Set pin to logic low.
void setHigh ()
Set pin to logic high.
void toggle ()
Toggle pin state.
uint8_t isHigh ()
Check if pin is logic high.
uint8_t isLow ()
Check if pin is logic low.
uint8_t getPinNumber ()
Get pin number.
Private Attributes
const Port & mr_portName
constant reference to port object
const uint8_t m_pinNumber
pin number
Detailed Description
Definition at line 20 of file Pin.h.
Constructor & Destructor Documentation
Pin()
io::Pin::Pin (const uint8_t a_pinNumber, const Port & ar_portName)
Constructor.
Initalizes the pin object
@param ar_portName defines the port name of the avr chip
@param ar_pinNumber defines the pin number of the avr chip
Definition at line 4 of file Pin.cpp.
         : mr_portName(mr_portName), m_pinNumber(a_pinNumber)
{
}
 Pin()
io::Pin::~Pin ()
Destructor.
Definition at line 11 of file Pin.cpp.
{
}
Member Function Documentation
getPinNumber()
uint8_t io::Pin::getPinNumber ()
Get pin number.
Definition at line 73 of file Pin.cpp.
{
    return m_pinNumber;
}
Referenced by core::ADConverter::selectAnalogInput().
isHigh()
uint8_t io::Pin::isHigh ()
Check if pin is logic high.
Definition at line 63 of file Pin.cpp.
{
    return *mr_portName.mp_pinReg & (1 << m_pinNumber);
}
isLow()
uint8_t io::Pin::isLow ()
Check if pin is logic low.
Definition at line 68 of file Pin.cpp.
{
    return !(*mr_portName.mp_pinReg & (1 << m_pinNumber));
}
setHigh()
void io::Pin::setHigh ()
Set pin to logic high.
Definition at line 47 of file Pin.cpp.
{
    if (*mr_portName.mp_ddrReg & (1 << m_pinNumber))
    {
        *mr_portName.mp_portReg |= (1 << m_pinNumber);
    }
}
setLow()
void io::Pin::setLow ()
Set pin to logic low.
Definition at line 39 of file Pin.cpp.
{
    if (*mr_portName.mp_ddrReg & (1 << m_pinNumber))
    {
        *mr_portName.mp_portReg &= ~(1 << m_pinNumber);
    }
}
toggle()
void io::Pin::toggle ()
Toggle pin state.
Definition at line 55 of file Pin.cpp.
{
    if (*mr_portName.mp_ddrReg & (1 << m_pinNumber))
    {
        *mr_portName.mp_portReg ^= 1 << m_pinNumber;
    }
}
toInput()
void io::Pin::toInput (const uint8_t & ar_useInternalPullUp)
Configures pin to input.
Parameters
ar_useInternalPullUp indicates if internal pull up resistor is used
Definition at line 22 of file Pin.cpp.
{
    if (ar_useInternalPullUp)
    {
        *mr_portName.mp_portReg |= (1 << m_pinNumber);
        *mr_portName.mp_ddrReg &= ~(1 << m_pinNumber);
    }
    else
    {
        *mr_portName.mp_portReg &= ~(1 << m_pinNumber);
        *mr_portName.mp_ddrReg &= ~(1 << m_pinNumber);
    }
}
Referenced by component::PushButton::PushButton(), and core::ADConverter::selectAnalogInput().
toOutput()
void io::Pin::toOutput ()
Configures pin to output.
Definition at line 17 of file Pin.cpp.
{
    *mr_portName.mp_ddrReg |= (1 << m_pinNumber);
}
Referenced by component::Buzzer::Buzzer(), component::DCMotor::DCMotor(), component::Led::Led(), component::ServoMotor::ServoMotor(), and component::StepperMotor::StepperMotor().
Member Data Documentation
m_pinNumber
const uint8_t io::Pin::m_pinNumber [private]
pin number
Definition at line 66 of file Pin.h.
mr_portName
const Port& io::Pin::mr_portName [private]
constant reference to port object
Definition at line 65 of file Pin.h.