core::ADConverter Class Reference
#include <ADC.h>
Public Member Functions
void start ()
void stop ()
void selectReferenceVoltage (const referenceVoltage &ar_refVoltage)
void selectAnalogInput (io::Pin a_pin)
void selectClockPrescaler (const clockPrescaler &ar_clockPrescaler)
void enableConversionCompleteInterrupt (const uint8_t a_enable)
void enableAutoTrigger (const uint8_t a_enable)
void selectAutoTriggerSource (const autoTriggerSource &ar_autoTriggerSource)
uint8_t conversionComplete ()
void getConversionResult (uint16_t *ap_resultData, const resolution &ar_resolution=resolution::res_10bit)
Static Public Member Functions
static ADConverter & getInstance (const referenceVoltage &ar_refVoltage=referenceVoltage::AVCC, const clockPrescaler &ar_clockPrescaler=clockPrescaler::PS_128, const autoTriggerSource &ar_autoTriggerSource=autoTriggerSource::freeRunning, const io::Pin &ar_pin=io::Pin(0, io::PortC))
static void conversionCompleteServiceRoutine () __asm__(STR(ADC_CONVERSION_COMPLETE_INTERRUPT)) __attribute__((__signal__
Public Attributes
static void __used__
static void __externally_visible__
Private Member Functions
ADConverter (const referenceVoltage &ar_refVoltage, const clockPrescaler &ar_clockPrescaler, const autoTriggerSource &ar_autoTriggerSource, const io::Pin &ar_pin)
~ADConverter ()
Destructor.
ADConverter (const ADConverter &)
Overried Copy constructor.
const ADConverter & operator= (const ADConverter &)
Override assign operator.
Static Private Attributes
static volatile uint16_t * mp_conversionResult = nullptr
pointer to receiver buffer
static uint8_t m_resolution = 10
pointer to receiver buffer
static volatile uint8_t m_conversionComplete = 0
ready to receive flag
Detailed Description
Definition at line 129 of file ADC.h.
Constructor & Destructor Documentation
ADConverter() [1/2]
core::ADConverter::ADConverter (const referenceVoltage & ar_refVoltage, const clockPrescaler & ar_clockPrescaler, const autoTriggerSource & ar_autoTriggerSource, const io::Pin & ar_pin) [private]
Definition at line 23 of file ADC.cpp.
{
    core::MCU::enableADC(1);
    selectAnalogInput(ar_pin);
    selectReferenceVoltage(ar_refVoltage);
    selectClockPrescaler(ar_clockPrescaler);
    enableAutoTrigger(1);
    selectAutoTriggerSource(ar_autoTriggerSource);
    sei();
    enableConversionCompleteInterrupt(1);
}
References core::MCU::enableADC().
 ADConverter()
core::ADConverter::~ADConverter () [private]
Destructor.
Definition at line 41 of file ADC.cpp.
{
}
ADConverter() [2/2]
core::ADConverter::ADConverter (const ADConverter &) [private]
Overried Copy constructor.
Member Function Documentation
conversionComplete()
uint8_t core::ADConverter::conversionComplete ()
Definition at line 255 of file ADC.cpp.
{
    return m_conversionComplete;
}
conversionCompleteServiceRoutine()
void core::ADConverter::conversionCompleteServiceRoutine () [static]
Definition at line 109 of file ADC.cpp.
{
    static uint32_t l_resultData = 0;
    static uint16_t l_resultDataIndex = 0;
    m_conversionComplete = 0;
    switch (m_resolution)
    {
        case 8:
        {
            *mp_conversionResult = ADC >> 8;
            m_conversionComplete = 1;
            break;
        }
        case 9:
        {
            *mp_conversionResult = ADC >> 7;
            m_conversionComplete = 1;
            break;
        }
        case 10:
        {
            *mp_conversionResult = ADC;
            m_conversionComplete = 1;
            break;
        }
        case 11:
        {
            if (l_resultDataIndex < 4)
            {
                l_resultData += ADC;
                l_resultDataIndex++;
            }
            else
            {
                *mp_conversionResult = l_resultData >> 1;
                l_resultData = 0;
                l_resultDataIndex = 0;
                m_conversionComplete = 1;
            }
            break;
        }
        case 12:
        {
            if (l_resultDataIndex < 16)
            {
                l_resultData += ADC;
                l_resultDataIndex++;
            }
            else
            {
                *mp_conversionResult = l_resultData >> 2;
                l_resultData = 0;
                l_resultDataIndex = 0;
                m_conversionComplete = 1;
            }
            break;
        }
        case 13:
        {
            if (l_resultDataIndex < 64)
            {
                l_resultData += ADC;
                l_resultDataIndex++;
            }
            else
            {
                *mp_conversionResult = l_resultData >> 3;
                l_resultData = 0;
                l_resultDataIndex = 0;
                m_conversionComplete = 1;
            }
            break;
        }
        case 14:
        {
            if (l_resultDataIndex < 256)
            {
                l_resultData += ADC;
                l_resultDataIndex++;
            }
            else
            {
                *mp_conversionResult = l_resultData >> 4;
                l_resultData = 0;
                l_resultDataIndex = 0;
                m_conversionComplete = 1;
            }
            break;
        }
        case 15:
        {
            if (l_resultDataIndex < 1024)
            {
                l_resultData += ADC;
                l_resultDataIndex++;
            }
            else
            {
                *mp_conversionResult = l_resultData >> 5;
                l_resultData = 0;
                l_resultDataIndex = 0;
                m_conversionComplete = 1;
            }
            break;
        }
        case 16:
        {
            if (l_resultDataIndex < 4096)
            {
                l_resultData += ADC;
                l_resultDataIndex++;
            }
            else
            {
                *mp_conversionResult = l_resultData >> 6;
                l_resultData = 0;
                l_resultDataIndex = 0;
                m_conversionComplete = 1;
            }
            break;
        }
    }
}
enableAutoTrigger()
void core::ADConverter::enableAutoTrigger (const uint8_t a_enable)
Definition at line 73 of file ADC.cpp.
{
    if (a_enable) {
        ADC_ENABLE_AUTOTRIGGER;
    } else {
        ADC_DISABLE_AUTOTRIGGER;
    }
}
References ADC_DISABLE_AUTOTRIGGER, and ADC_ENABLE_AUTOTRIGGER.
enableConversionCompleteInterrupt()
void core::ADConverter::enableConversionCompleteInterrupt (const uint8_t a_enable)
Definition at line 84 of file ADC.cpp.
{
    if (a_enable) {
        ADC_ENABLE_CONVERSION_COMPLETE_INTERRUPT;
    } else {
        ADC_DISABLE_CONVERSION_COMPLETE_INTERRUPT;
    }
}
References ADC_DISABLE_CONVERSION_COMPLETE_INTERRUPT, and ADC_ENABLE_CONVERSION_COMPLETE_INTERRUPT.
getConversionResult()
void core::ADConverter::getConversionResult (uint16_t * ap_resultData, const resolution & ar_resolution = resolution::res_10bit)
Definition at line 262 of file ADC.cpp.
{
    mp_conversionResult = ap_resultData;
    switch (ar_resolution)
    {
        case core::resolution::res_8bit:
        {
            ADC_ADJUST_RESULT_LEFT;
            m_resolution = 8;
            break;
        }
        case core::resolution::res_9bit:
        {
            ADC_ADJUST_RESULT_LEFT;
            m_resolution = 9;
            break;
        }
        case core::resolution::res_10bit:
        {
            ADC_ADJUST_RESULT_RIGHT;
            m_resolution = 10;
            break;
        }
        case core::resolution::res_11bit:
        {
            m_resolution = 11;
            break;
        }
        case core::resolution::res_12bit:
        {
            m_resolution = 12;
            break;
        }
        case core::resolution::res_13bit:
        {
            m_resolution = 13;
            break;
        }
        case core::resolution::res_14bit:
        {
            m_resolution = 14;
            break;
        }
        case core::resolution::res_15bit:
        {
            m_resolution = 15;
            break;
        }
        case core::resolution::res_16bit:
        {
            m_resolution = 16;
            break;
        }
    }
}
References ADC_ADJUST_RESULT_LEFT, ADC_ADJUST_RESULT_RIGHT, core::res_10bit, core::res_11bit, core::res_12bit, core::res_13bit, core::res_14bit, core::res_15bit, core::res_16bit, core::res_8bit, and core::res_9bit.
getInstance()
core::ADConverter & core::ADConverter::getInstance (const referenceVoltage & ar_refVoltage = referenceVoltage::AVCC, const clockPrescaler & ar_clockPrescaler = clockPrescaler::PS_128, const autoTriggerSource & ar_autoTriggerSource = autoTriggerSource::freeRunning, const io::Pin & ar_pin = io::Pin(0,io::PortC)) [static]
Definition at line 9 of file ADC.cpp.
{
    static ADConverter l_instance(ar_refVoltage,
                                  ar_clockPrescaler,
                                  ar_autoTriggerSource,
                                  ar_pin);
    return l_instance;
}
operator=()
const ADConverter& core::ADConverter::operator= (const ADConverter &) [private]
Override assign operator.
selectAnalogInput()
void core::ADConverter::selectAnalogInput (io::Pin a_pin)
Definition at line 53 of file ADC.cpp.
{
    a_pin.toInput(0);
    ADC_SELECT_ANALOG_INPUT(a_pin.getPinNumber());
    ADC_DISABLE_DIGITAL_INPUT_REGISTER(a_pin.getPinNumber());
}
References ADC_DISABLE_DIGITAL_INPUT_REGISTER, ADC_SELECT_ANALOG_INPUT, io::Pin::getPinNumber(), and io::Pin::toInput().
selectAutoTriggerSource()
void core::ADConverter::selectAutoTriggerSource (const autoTriggerSource & ar_autoTriggerSource)
Definition at line 102 of file ADC.cpp.
{
    ADC_SELECT_AUTO_TRIGGER_SOURCE(static_cast<uint8_t>(ar_autoTriggerSource));
}
References ADC_SELECT_AUTO_TRIGGER_SOURCE.
selectClockPrescaler()
void core::ADConverter::selectClockPrescaler (const clockPrescaler & ar_clockPrescaler)
Definition at line 95 of file ADC.cpp.
{
    ADC_SELECT_CLOCK_PRESCALER(static_cast<uint8_t>(ar_clockPrescaler));
}
References ADC_SELECT_CLOCK_PRESCALER.
selectReferenceVoltage()
void core::ADConverter::selectReferenceVoltage (const referenceVoltage & ar_refVoltage)
Definition at line 47 of file ADC.cpp.
{
    ADC_SELECT_REF_VOLTAGE(static_cast<uint8_t>(ar_refVoltage));
}
References ADC_SELECT_REF_VOLTAGE.
start()
void core::ADConverter::start ()
Definition at line 61 of file ADC.cpp.
{
    ADC_ENABLE;
    ADC_START_CONVERSION;
}
References ADC_ENABLE, and ADC_START_CONVERSION.
stop()
void core::ADConverter::stop ()
Definition at line 67 of file ADC.cpp.
{
    ADC_STOP_CONVERSION;
    ADC_DISABLE;
}
References ADC_DISABLE, and ADC_STOP_CONVERSION.
Member Data Documentation
__externally_visible__
void core::ADConverter::__externally_visible__
Definition at line 160 of file ADC.h.
__used__
void core::ADConverter::__used__
Definition at line 160 of file ADC.h.
m_conversionComplete
volatile uint8_t core::ADConverter::m_conversionComplete = 0 [static], [private]
ready to receive flag
Definition at line 192 of file ADC.h.
m_resolution
uint8_t core::ADConverter::m_resolution = 10 [static], [private]
pointer to receiver buffer
Definition at line 190 of file ADC.h.
mp_conversionResult
volatile uint16_t * core::ADConverter::mp_conversionResult = nullptr [static], [private]
pointer to receiver buffer
Definition at line 187 of file ADC.h.